### ISSUE TITLE
Cannot run code chunks in R console kernal

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#12]
https://eia.scio.services:18002/user/p.steward@cgiar.org/lab

shift+enter doing nothing in R console, I close and restarted the kernal, still have the same problem.

**Comment by agelosnm** [comment]
@peetmate We could not recreate the issue. Execution of R scripts is performing normally, depending on what you are actually trying to execute. For instance, I ran a simple "library" command.

Could you please inform us what you did exactly in order to try to understand and reproduce the issue you faced?

**Comment by peetmate** [comment]
I opened my server as normal, I created a console for my R editor, shift+enter does not run a line of code in the console.

For example 1+1 does not even work. 

The console seems to be frozen.

If I restart the kernal the issue does not resolve

**Comment by peetmate** [comment]
Restarting my servers is taking a long time >5min

**Comment by agelosnm** [comment]
Kubernets resources caching was producing such issues. Resources have been re-arranged and such operations should be reproduced to have the system tested.
