### ISSUE TITLE
File browser frozen

### ISSUE THREAD

**Issue by peetmate** [SCiO-systems/eiaspatial-notebook#15]
My file browser is unresponsive, refresh doesn't work.

Do I have to restart my server yet again?

**Comment by peetmate** [comment]
getting an error - Delete Failed, failed to fetch

**Comment by sotkonstantinidis** [comment]
@peetmate most of the issues you mentioned seem have to do with the communication between the user interface (which is executed on the browser) and you  "environment" (which sits on our infrastructure). 

It would help, to understand what is going on and find a solution, to arrange a telco, and check step-by-step the issues. Due to the nature of the issues it is almost imposible to recreate them.

**Comment by peetmate** [comment]
I am seeing "Initialized (additional servers needed)" where it should say R Idle/R Busy at the bottom of the screen

LSP servers
Missing 1
r
documentation: language servers

**Comment by sotkonstantinidis** [comment]
@peetmate this has to do with the autocomplete functionality, which is yet not ready. Nothing to do with the actual infrastructure/servers

**Comment by peetmate** [comment]
Ok, telco is fine. please suggest a time via email
